[2024-03-30T02:06:17.765+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: migrate_student_data_to_snowflake.load_data_to_snowflake manual__2024-03-30T02:06:10.866696+00:00 [queued]>
[2024-03-30T02:06:17.772+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: migrate_student_data_to_snowflake.load_data_to_snowflake manual__2024-03-30T02:06:10.866696+00:00 [queued]>
[2024-03-30T02:06:17.773+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-30T02:06:17.782+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): load_data_to_snowflake> on 2024-03-30 02:06:10.866696+00:00
[2024-03-30T02:06:17.787+0000] {standard_task_runner.py:60} INFO - Started process 79 to run task
[2024-03-30T02:06:17.789+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'migrate_student_data_to_snowflake', 'load_data_to_snowflake', 'manual__2024-03-30T02:06:10.866696+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/student_data_migration.py', '--cfg-path', '/tmp/tmpbu1s2dp5']
[2024-03-30T02:06:17.791+0000] {standard_task_runner.py:88} INFO - Job 158: Subtask load_data_to_snowflake
[2024-03-30T02:06:17.828+0000] {task_command.py:423} INFO - Running <TaskInstance: migrate_student_data_to_snowflake.load_data_to_snowflake manual__2024-03-30T02:06:10.866696+00:00 [running]> on host 0d6dcae834a4
[2024-03-30T02:06:17.930+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='migrate_student_data_to_snowflake' AIRFLOW_CTX_TASK_ID='load_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T02:06:10.866696+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-30T02:06:10.866696+00:00'
[2024-03-30T02:06:17.931+0000] {connection.py:386} INFO - Snowflake Connector for Python Version: 3.7.1, Python Version: 3.8.19, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.34
[2024-03-30T02:06:17.932+0000] {connection.py:1211} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-03-30T02:06:18.843+0000] {cursor.py:1032} INFO - query: [USE DATABASE VIEWS_STUDENTS]
[2024-03-30T02:06:18.979+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T02:06:18.980+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-03-30T02:06:18.981+0000] {cursor.py:1032} INFO - query: [USE SCHEMA STUDENTS_SEMANTIC]
[2024-03-30T02:06:19.096+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T02:06:19.097+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-03-30T02:06:19.098+0000] {cursor.py:1032} INFO - query: [CREATE OR REPLACE TABLE FINAL_MERGED ( student_id VARCHAR, name VARCHAR, grades ...]
[2024-03-30T02:06:19.412+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T02:06:19.413+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-03-30T02:06:19.414+0000] {cursor.py:1032} INFO - query: [CREATE TEMP STAGE /* Python:snowflake.connector.pandas_tools.write_pandas() */ "...]
[2024-03-30T02:06:19.547+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T02:06:19.548+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-03-30T02:06:19.552+0000] {cursor.py:1032} INFO - query: [PUT /* Python:snowflake.connector.pandas_tools.write_pandas() */ 'file:///tmp/tm...]
[2024-03-30T02:06:19.731+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T02:06:19.981+0000] {cursor.py:1032} INFO - query: [COPY INTO "STUDENTS_SEMANTIC"."FINAL_MERGED" /* Python:snowflake.connector.panda...]
[2024-03-30T02:06:20.103+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T02:06:20.111+0000] {student_data_migration.py:139} ERROR - Error loading data into Snowflake: 000904 (42000): 01b352f9-0000-3e0f-0000-000049913611: SQL compilation error: error line 1 at position 107
invalid identifier '"student_id"'
[2024-03-30T02:06:20.112+0000] {connection.py:734} INFO - closed
[2024-03-30T02:06:20.147+0000] {connection.py:740} INFO - No async queries seem to be running, deleting session
[2024-03-30T02:06:20.197+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/student_data_migration.py", line 132, in load_data_to_snowflake
    write_pandas(conn=conn,
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/pandas_tools.py", line 438, in write_pandas
    copy_results = cursor.execute(copy_into_sql, _is_internal=True).fetchall()
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 1136, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 000904 (42000): 01b352f9-0000-3e0f-0000-000049913611: SQL compilation error: error line 1 at position 107
invalid identifier '"student_id"'
[2024-03-30T02:06:20.206+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=migrate_student_data_to_snowflake, task_id=load_data_to_snowflake, execution_date=20240330T020610, start_date=20240330T020617, end_date=20240330T020620
[2024-03-30T02:06:20.221+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 158 for task load_data_to_snowflake (000904 (42000): 01b352f9-0000-3e0f-0000-000049913611: SQL compilation error: error line 1 at position 107
invalid identifier '"student_id"'; 79)
[2024-03-30T02:06:20.253+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-30T02:06:20.269+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
