[2024-03-30T01:51:12.245+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: migrate_student_data_to_snowflake.load_data_to_snowflake manual__2024-03-30T01:51:05.433669+00:00 [queued]>
[2024-03-30T01:51:12.251+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: migrate_student_data_to_snowflake.load_data_to_snowflake manual__2024-03-30T01:51:05.433669+00:00 [queued]>
[2024-03-30T01:51:12.252+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-30T01:51:12.262+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): load_data_to_snowflake> on 2024-03-30 01:51:05.433669+00:00
[2024-03-30T01:51:12.266+0000] {standard_task_runner.py:60} INFO - Started process 107 to run task
[2024-03-30T01:51:12.270+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'migrate_student_data_to_snowflake', 'load_data_to_snowflake', 'manual__2024-03-30T01:51:05.433669+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/student_data_migration.py', '--cfg-path', '/tmp/tmptv285x3e']
[2024-03-30T01:51:12.272+0000] {standard_task_runner.py:88} INFO - Job 143: Subtask load_data_to_snowflake
[2024-03-30T01:51:12.309+0000] {task_command.py:423} INFO - Running <TaskInstance: migrate_student_data_to_snowflake.load_data_to_snowflake manual__2024-03-30T01:51:05.433669+00:00 [running]> on host 4eb3fd2c57a4
[2024-03-30T01:51:12.421+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='migrate_student_data_to_snowflake' AIRFLOW_CTX_TASK_ID='load_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T01:51:05.433669+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-30T01:51:05.433669+00:00'
[2024-03-30T01:51:12.423+0000] {connection.py:386} INFO - Snowflake Connector for Python Version: 3.7.1, Python Version: 3.8.19, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.34
[2024-03-30T01:51:12.424+0000] {connection.py:1211} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-03-30T01:51:13.265+0000] {cursor.py:1032} INFO - query: [CREATE OR REPLACE TABLE FINAL_MERGED ( student_id VARCHAR, name VARCHAR, grades ...]
[2024-03-30T01:51:13.400+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T01:51:13.407+0000] {student_data_migration.py:139} ERROR - Error loading data into Snowflake: 090105 (22000): 01b352ea-0000-3e11-0000-000049912635: Cannot perform CREATE TABLE. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.
[2024-03-30T01:51:13.407+0000] {connection.py:734} INFO - closed
[2024-03-30T01:51:13.439+0000] {connection.py:740} INFO - No async queries seem to be running, deleting session
[2024-03-30T01:51:13.510+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/student_data_migration.py", line 122, in load_data_to_snowflake
    cursor.execute("""
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 1136, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 090105 (22000): 01b352ea-0000-3e11-0000-000049912635: Cannot perform CREATE TABLE. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.
[2024-03-30T01:51:13.534+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=migrate_student_data_to_snowflake, task_id=load_data_to_snowflake, execution_date=20240330T015105, start_date=20240330T015112, end_date=20240330T015113
[2024-03-30T01:51:13.564+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 143 for task load_data_to_snowflake (090105 (22000): 01b352ea-0000-3e11-0000-000049912635: Cannot perform CREATE TABLE. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.; 107)
[2024-03-30T01:51:13.608+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-30T01:51:13.622+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
