[2024-03-30T02:25:28.571+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: migrate_student_data_to_snowflake.load_data_to_snowflake manual__2024-03-30T02:25:21.990037+00:00 [queued]>
[2024-03-30T02:25:28.579+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: migrate_student_data_to_snowflake.load_data_to_snowflake manual__2024-03-30T02:25:21.990037+00:00 [queued]>
[2024-03-30T02:25:28.580+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-30T02:25:28.603+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): load_data_to_snowflake> on 2024-03-30 02:25:21.990037+00:00
[2024-03-30T02:25:28.612+0000] {standard_task_runner.py:60} INFO - Started process 90 to run task
[2024-03-30T02:25:28.616+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'migrate_student_data_to_snowflake', 'load_data_to_snowflake', 'manual__2024-03-30T02:25:21.990037+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/student_data_migration.py', '--cfg-path', '/tmp/tmpb8mqyk7m']
[2024-03-30T02:25:28.619+0000] {standard_task_runner.py:88} INFO - Job 182: Subtask load_data_to_snowflake
[2024-03-30T02:25:28.668+0000] {task_command.py:423} INFO - Running <TaskInstance: migrate_student_data_to_snowflake.load_data_to_snowflake manual__2024-03-30T02:25:21.990037+00:00 [running]> on host ad4496215849
[2024-03-30T02:25:28.799+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='migrate_student_data_to_snowflake' AIRFLOW_CTX_TASK_ID='load_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T02:25:21.990037+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-30T02:25:21.990037+00:00'
[2024-03-30T02:25:28.800+0000] {connection.py:386} INFO - Snowflake Connector for Python Version: 3.7.1, Python Version: 3.8.19, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.34
[2024-03-30T02:25:28.801+0000] {connection.py:1211} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-03-30T02:25:29.685+0000] {cursor.py:1032} INFO - query: [CREATE DATABASE IF NOT EXISTS VIEWS_STUDENTS]
[2024-03-30T02:25:29.792+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T02:25:29.793+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-03-30T02:25:29.793+0000] {cursor.py:1032} INFO - query: [USE DATABASE VIEWS_STUDENTS]
[2024-03-30T02:25:29.892+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T02:25:29.893+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-03-30T02:25:29.893+0000] {cursor.py:1032} INFO - query: [CREATE SCHEMA IF NOT EXISTS STUDENTS_SEMANTIC]
[2024-03-30T02:25:29.971+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T02:25:29.972+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-03-30T02:25:29.972+0000] {cursor.py:1032} INFO - query: [USE SCHEMA STUDENTS_SEMANTIC]
[2024-03-30T02:25:30.061+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T02:25:30.062+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-03-30T02:25:30.063+0000] {cursor.py:1032} INFO - query: [CREATE OR REPLACE TABLE FINAL_MERGED ( student_id VARCHAR, name VARCHAR, grades ...]
[2024-03-30T02:25:30.382+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T02:25:30.383+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-03-30T02:25:30.391+0000] {student_data_migration.py:142} ERROR - Error loading data into Snowflake: 252004: 252004: Failed processing pyformat-parameters; 255001: 255001: Binding data in type (dict) is not supported.
[2024-03-30T02:25:30.391+0000] {connection.py:734} INFO - closed
[2024-03-30T02:25:30.424+0000] {connection.py:740} INFO - No async queries seem to be running, deleting session
[2024-03-30T02:25:30.479+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/connection.py", line 1517, in _process_params_pyformat
    ret = tuple(res)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/connection.py", line 1563, in _process_single_param
    return _quote(escape(to_snowflake(param)))
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/converter.py", line 481, in to_snowflake
    return getattr(self, f"_{type_name}_to_snowflake")(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/converter.py", line 653, in __getattr__
    raise ProgrammingError(
snowflake.connector.errors.ProgrammingError: 255001: 255001: Binding data in type (dict) is not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/student_data_migration.py", line 137, in load_data_to_snowflake
    cursor.executemany(query, data)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 1430, in executemany
    fmt % self._connection._process_params_pyformat(param, self)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/connection.py", line 1521, in _process_params_pyformat
    Error.errorhandler_wrapper(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 252004: 252004: Failed processing pyformat-parameters; 255001: 255001: Binding data in type (dict) is not supported.
[2024-03-30T02:25:30.487+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=migrate_student_data_to_snowflake, task_id=load_data_to_snowflake, execution_date=20240330T022521, start_date=20240330T022528, end_date=20240330T022530
[2024-03-30T02:25:30.498+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 182 for task load_data_to_snowflake (252004: 252004: Failed processing pyformat-parameters; 255001: 255001: Binding data in type (dict) is not supported.; 90)
[2024-03-30T02:25:30.517+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-30T02:25:30.530+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
