[2024-03-30T01:15:50.676+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: migrate_student_data_to_snowflake.load_data_to_snowflake manual__2024-03-30T01:10:39.326862+00:00 [queued]>
[2024-03-30T01:15:50.683+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: migrate_student_data_to_snowflake.load_data_to_snowflake manual__2024-03-30T01:10:39.326862+00:00 [queued]>
[2024-03-30T01:15:50.684+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2024-03-30T01:15:50.692+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): load_data_to_snowflake> on 2024-03-30 01:10:39.326862+00:00
[2024-03-30T01:15:50.697+0000] {standard_task_runner.py:60} INFO - Started process 178 to run task
[2024-03-30T01:15:50.699+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'migrate_student_data_to_snowflake', 'load_data_to_snowflake', 'manual__2024-03-30T01:10:39.326862+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/student_data_migration.py', '--cfg-path', '/tmp/tmp329k60eg']
[2024-03-30T01:15:50.701+0000] {standard_task_runner.py:88} INFO - Job 111: Subtask load_data_to_snowflake
[2024-03-30T01:15:50.740+0000] {task_command.py:423} INFO - Running <TaskInstance: migrate_student_data_to_snowflake.load_data_to_snowflake manual__2024-03-30T01:10:39.326862+00:00 [running]> on host c2c92d6aa5d1
[2024-03-30T01:15:50.839+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='migrate_student_data_to_snowflake' AIRFLOW_CTX_TASK_ID='load_data_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T01:10:39.326862+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-30T01:10:39.326862+00:00'
[2024-03-30T01:15:50.841+0000] {connection.py:386} INFO - Snowflake Connector for Python Version: 3.7.1, Python Version: 3.8.19, Platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.34
[2024-03-30T01:15:50.842+0000] {connection.py:1211} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-03-30T01:15:52.470+0000] {cursor.py:1032} INFO - query: [CREATE DATABASE IF NOT EXISTS VIEWS_STUDENTS]
[2024-03-30T01:15:52.647+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T01:15:52.648+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-03-30T01:15:52.648+0000] {cursor.py:1032} INFO - query: [USE DATABASE VIEWS_STUDENTS]
[2024-03-30T01:15:52.755+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T01:15:52.756+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-03-30T01:15:52.757+0000] {cursor.py:1032} INFO - query: [CREATE SCHEMA IF NOT EXISTS STUDENTS_SEMANTIC]
[2024-03-30T01:15:52.885+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T01:15:52.886+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-03-30T01:15:52.886+0000] {cursor.py:1032} INFO - query: [USE SCHEMA STUDENTS_SEMANTIC]
[2024-03-30T01:15:53.054+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T01:15:53.055+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-03-30T01:15:53.055+0000] {cursor.py:1032} INFO - query: [CREATE TABLE IF NOT EXISTS FINAL_MERGED ( student_id VARCHAR, grades VARCHAR, mi...]
[2024-03-30T01:15:53.167+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T01:15:53.168+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-03-30T01:15:53.169+0000] {cursor.py:1032} INFO - query: [CREATE TEMP STAGE /* Python:snowflake.connector.pandas_tools.write_pandas() */ "...]
[2024-03-30T01:15:53.319+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T01:15:53.320+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-03-30T01:15:53.324+0000] {cursor.py:1032} INFO - query: [PUT /* Python:snowflake.connector.pandas_tools.write_pandas() */ 'file:///tmp/tm...]
[2024-03-30T01:15:53.516+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T01:15:53.925+0000] {cursor.py:1032} INFO - query: [COPY INTO "VIEWS_STUDENTS"."STUDENTS_SEMANTIC"."FINAL_MERGED" /* Python:snowflak...]
[2024-03-30T01:15:54.075+0000] {cursor.py:1045} INFO - query execution done
[2024-03-30T01:15:54.083+0000] {student_data_migration.py:144} ERROR - Error loading data into Snowflake: 000904 (42000): 01b352c7-0000-3e0f-0000-000049913495: SQL compilation error: error line 1 at position 124
invalid identifier '"student_id"'
[2024-03-30T01:15:54.083+0000] {connection.py:734} INFO - closed
[2024-03-30T01:15:54.208+0000] {connection.py:740} INFO - No async queries seem to be running, deleting session
[2024-03-30T01:15:54.272+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/student_data_migration.py", line 136, in load_data_to_snowflake
    success, nchunks, nrows, _ = write_pandas(conn=conn
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/pandas_tools.py", line 438, in write_pandas
    copy_results = cursor.execute(copy_into_sql, _is_internal=True).fetchall()
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 1136, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 000904 (42000): 01b352c7-0000-3e0f-0000-000049913495: SQL compilation error: error line 1 at position 124
invalid identifier '"student_id"'
[2024-03-30T01:15:54.280+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=migrate_student_data_to_snowflake, task_id=load_data_to_snowflake, execution_date=20240330T011039, start_date=20240330T011550, end_date=20240330T011554
[2024-03-30T01:15:54.291+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 111 for task load_data_to_snowflake (000904 (42000): 01b352c7-0000-3e0f-0000-000049913495: SQL compilation error: error line 1 at position 124
invalid identifier '"student_id"'; 178)
[2024-03-30T01:15:54.330+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-30T01:15:54.343+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
